# Generated by Django 3.1.3 on 2021-01-27 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('aboutMe', models.TextField(blank=True, max_length=199, null=True)),
                ('birthDay', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(default='media/profilePhoto/default.jpg', upload_to='media/profilePhoto')),
                ('city', models.CharField(blank=True, max_length=99, null=True)),
                ('country', models.CharField(blank=True, max_length=99, null=True)),
            ],
        ),
    ]
