# Generated by Django 3.1.3 on 2021-01-29 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='user')),
                ('biography', models.TextField(blank=True, max_length=399, null=True)),
                ('profileAvatar', models.ImageField(blank=True, default='profilePhoto/default.jpg', upload_to='profilePhoto')),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('currentLocation', models.CharField(blank=True, max_length=99, null=True)),
                ('countryOrigin', models.CharField(blank=True, max_length=99, null=True)),
            ],
        ),
    ]
