# Generated by Django 3.1.3 on 2021-01-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konto', '0002_auto_20210114_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
