# Generated by Django 3.1.3 on 2021-01-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konto', '0003_auto_20210118_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
