# Generated by Django 3.1.3 on 2021-02-14 14:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('konto', '0006_auto_20210206_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='countryOrigin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
