# Generated by Django 3.1.3 on 2021-02-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konto', '0008_auto_20210218_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='currentLocation',
            new_name='city',
        ),
    ]
