# Generated by Django 3.1.3 on 2021-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konto', '0009_auto_20210220_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='O mnie'),
        ),
    ]
