# Generated by Django 3.1.3 on 2021-02-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konto', '0010_auto_20210220_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='O mnie'),
        ),
    ]
