# Generated by Django 3.1.3 on 2021-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konto', '0011_auto_20210227_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(blank=True, help_text='dd-mm-yy', null=True, verbose_name='Data urodzin'),
        ),
    ]
