# Generated by Django 3.1.3 on 2021-02-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konto', '0012_auto_20210227_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthDate',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzin'),
        ),
    ]
