# Generated by Django 3.1.3 on 2021-01-31 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postLikes',
            field=models.ManyToManyField(related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
