# Generated by Django 3.1.3 on 2021-04-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postUrl',
        ),
    ]
