# Generated by Django 3.1.3 on 2021-01-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210121_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
