# Generated by Django 3.1.3 on 2021-02-07 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_post_postlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postLikes',
            field=models.ManyToManyField(blank=True, related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
