# Generated by Django 3.1.3 on 2021-02-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20210207_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImages',
            field=models.ImageField(blank=True, null=True, upload_to='media/Images'),
        ),
    ]
