# Generated by Django 3.1.3 on 2021-02-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_postimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImages',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
