# Generated by Django 3.1.3 on 2021-02-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20210214_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postImages',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/#D/'),
        ),
    ]
