# Generated by Django 3.1.3 on 2021-02-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20210214_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
