# Generated by Django 3.1.3 on 2021-02-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20210214_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentContent',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='postContent',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImages',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/', verbose_name=''),
        ),
    ]
