# Generated by Django 3.1.3 on 2021-02-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20210218_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postContent',
            field=models.TextField(max_length=200, verbose_name=''),
        ),
    ]
