# Generated by Django 3.1.3 on 2021-02-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='create_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='target_id',
            new_name='targetID',
        ),
    ]
